Brigade
VK-BMSTU-QA/homework-selenium-2023-autumn pull request #7
Opened 2023-12-24 16:10 UTC by marcussss1

2023-12-27 07:32 UTC, alexey-ershkov requested changes

2023-12-27 07:32 UTC, alexey-ershkov commented on hw/code/test_campaign.py
> +            advertisements_page.locators.CREATE_CAMPAIGN_ADVERTISEMENTS_LONG_FIELD_LABEL
Протекает концепция PageObject, ток сама страница должна знать про локаторы и как что-то в ней найти, а текст уже использует человекопонятные функции без технических деталей

в данном случае оно все должно ухеать в страницу с названием типа `get_long_field_label`, в котором уже как раз find_elem_by_locator

Это по всем тестам, а не только здесь

2023-12-27 07:32 UTC, alexey-ershkov commented on hw/code/ui/pages/campaign/create/groups_page.py
> +        return CreateCampaignGroupsPage(self.driver)
Перенос в конце строки потерял

2023-12-27 07:32 UTC, alexey-ershkov commented on hw/code/ui/pages/main_page.py
> +from ui.pages.base_page import BasePage
А эта страница точно нужна?

2023-12-28 04:55 UTC, alexey-ershkov requested changes
Приветы, сейчас уже прям хорошо, нашел последний момент

2023-12-28 04:55 UTC, alexey-ershkov commented on hw/code/test_campaign.py
> +        draft_name = f'Кампания {utils.get_today()}'
кажется лучше в страницу перенести функцию получения названия, а то если в функциях создания поменяется генерация имени - все тесты попадают

2023-12-28 08:05 UTC, alexey-ershkov commented
Аппрув

2023-12-28 16:32 UTC, dkotegov requested changes

2023-12-28 16:32 UTC, dkotegov commented on hw/code/test_campaign.py
> +        campaign_page.delete_draft(campaign_page.get_campaign_title())
Если ассерт упадет, то эта строчка не выполнится

2023-12-28 16:32 UTC, dkotegov commented
Ладно

2023-12-28 16:32 UTC, closed without merging