Techokaif
VK-BMSTU-QA/homework-selenium-2023-autumn pull request #9
Opened 2023-12-27 23:37 UTC by GodofRussia

Написали тесты на VK ADS

Выполнили: 
Игнат Роменский, Илья Мочалов, Степан Попов, Ярослав Кузьмин

Ссылки на чек-листы:
https://github.com/VK-BMSTU-QA/homework-3-autumn-2023/pull/15
https://github.com/VK-BMSTU-QA/homework-3-autumn-2023/pull/22
https://github.com/VK-BMSTU-QA/homework-3-autumn-2023/pull/23
https://github.com/VK-BMSTU-QA/homework-3-autumn-2023/pull/24

2023-12-27 23:38 UTC, KolobokMysnoy commented
Approve

2023-12-27 23:39 UTC, GodofRussia commented
Approved

2023-12-28 06:06 UTC, stepanpopov commented
approve

2023-12-28 08:18 UTC, yarikTri commented
Approve

2023-12-28 16:10 UTC, dkotegov requested changes
убрать слипы
исправить работу с PageObject, работа с браузером должна быть в пейджах, а логика в тестах
починить падающие тесты и убедиться что все тесты проходят
исправить локаторы
убрать дебажный код и дебажные принты
провести ревью между собой
константы вынести отдельно
pep8

2023-12-28 16:10 UTC, dkotegov commented on hw/code/tests/test_company.py
> +            except:
Перехватывать всё плохо

2023-12-28 16:10 UTC, dkotegov commented on hw/code/ui/locators/basic.py
> +    PYTHON_CONSOLE = (By.ID, "hterm:row-nodes")'''
?

2023-12-28 16:11 UTC, GodofRussia commented
скрины и дебаг стектрейс для определения падения тестов

2023-12-28 16:16 UTC, GodofRussia commented
ассерты можно ставить по несколько штук, не ставить and и проверку в одном ассерте, разделять их

2024-01-14 18:56 UTC, stepanpopov commented
ревью между участниками проводилось в репозитории

2024-01-14 18:59 UTC, stepanpopov commented
аппрув

2024-01-14 19:00 UTC, yarikTri commented
Аппрув

2024-01-14 19:00 UTC, KolobokMysnoy commented
Аппрув

2024-01-14 19:00 UTC, GodofRussia commented
апппрувчик

2024-01-14 19:04 UTC, stepanpopov commented
- исправили все замечания
- перенесли работу с браузером в base page и убрали бразуерную логику из base page
- сделали логгер
- сделали создание скриншотов при падающих тестах
- убрали зависимость тестов друг от друга
- вынесли константы в отдельный файл
- провели ревью между собой
- вынесли загружаемые файлы-моки  в отдельную папку

2024-01-16 15:10 UTC, stepanpopov commented
исправили флакающие тесты

2024-01-17 00:46 UTC, closed without merging

2024-01-17 00:46 UTC, dkotegov commented
Принято